services:
    web:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./data:/var/www/html/storage
        - .env:/var/www/html/.env
