services:
    web:
      build:
        context: .
        dockerfile: .deployment/docker/Dockerfile
      ports:
        - "80:80"
        - "443:443"
      environment:
        - APP_ENV=dev
        - APP_DEBUG=true
