#!/bin/bash

source db_dump_config

function run_command(){
    echo "[EXEC] $1"
    eval $1
}

run_command "ssh $DB_SERVER \"mysqldump -u $MYSQL_USERNAME --password='$MYSQL_PASSWORD' $1 > $FILENAME\""
run_command "rsync $DB_SERVER:~/$FILENAME ."
run_command "ssh $DB_SERVER 'rm $FILENAME'"



